### ISSUE TITLE
Evaluate Mutagen tunnels

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/dde#11]
https://mutagen.io/documentation/transports/tunnels

This would allow us to handle container restarts / recreation more gracefully. If we can somehow include the tunnel broker in the dde system compose stack, that would be optimal - until then we could make this optional, and allow users to specify their mutagen.io credentials.

**Comment by Ruesa18** [comment]
@s4mpl3d @lukasluecke It seems like these tunnels are not supported anymore. So my suggestion would be to close this issue.
What is your take on this?
