### ISSUE TITLE
use "docker-compose config" for analyzing configuration

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/dde#28]
instead of analyzing the YAML files use "docker-compose config".

`docker-compose config`, includes the `docker-compose.override.yml` file

**Comment by tuxes3** [comment]
Which commands are affected?

**Comment by Ruesa18** [comment]
@s4mpl3d Sadly we did this issue twice in #45 and #34 because the issues and the PRs were not properly linked or assigned to anyone
