### ISSUE TITLE
rename project:exec to project:shell

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/dde#35]
the command `project:exec` is ambiguous. 

project:exec make essentially a `docker compose exec sh`, so it opens a shell in the container.

to further develop dde i like to introduce a project-command #36  to execute a command in the container, for example `docker compose exec bin/console --help`. but how call this new project-command?

so to clarify the project-command i like to rename:

- `project:exec` to `project:shell`
- `project:exec-root` to `project:root-shell`

**Comment by s4mpl3d** [comment]
Nice idea :+1: 

Only thing i would change is `project:root-shell` => `project:shell-root`.
That way only the shell part changes and the rest stays the same. Also when sorting all commands, all shell command are grouped together

**Comment by tuxes3** [comment]
As long as shortcuts will still be possible i am ok with. 

`dde exec` or `dde shel` should still work.
