### ISSUE TITLE
Run commands on specific container

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/dde#4]
For multi-container projects (e.g. decoupled API/frontend) it should be possible to run `dde exec [container]` to get a shell session on that container.

**Comment by lukasluecke** [comment]
Possible solutions:
- `dde exec on=[container]`
  This uses the default argument handling of make (env variables), but introduces some cognitive overhead (need to remember parameter name)
- `dde exec [container]` and shell command parsing (https://stackoverflow.com/a/6273809)
  This allows for a cleaner syntax, but isn't really clean (breaks encapsulation, also will try to call the make action called `[container]` after the exec is finished)

I talked this over with @xarem and we came to the conclusion that it might make sense to transform the `dde` alias into a shell script / executable that handles these advanced use cases, while falling back to or calling make for the existing functionality. In the long run it might make sense to move the majority or all of the actions, but that can be discussed at a later point.

**Comment by lukasluecke** [comment]
Additionally this container selection might also make sense for `start`/`stop`, `log` and possibly others.

**Comment by 71m024** [comment]
I would realy appreciate the container selection for the `update` feature. 
The main reason for me are data-containers where i'm not able to mount the data to my host.

**Comment by Ruesa18** [comment]
@lukasluecke If I understand this issue correctly, this has become a feature of dde by now (`dde exec web`). But we could mention this in the documentation - it's missing there...

Also we should probably make a follow-up issue about the `start`/`stop`, `log` and `update` commands. This could really enhance the overall experience in my opinion 👍 
Other opinions?
