### ISSUE TITLE
system:update master checkout

### ISSUE THREAD

**Issue by marcwieland95** [whatwedo/dde#49]
I just had the issue that I had checked out a feature of the dde-system.

While trying to setup a project, things failed and I didn't know why. It ended up that I did not checkout the master branch.
I wrongly thought a `dde system:update` would reset the branch and update to the latest version in the master branch.

There are two options for me to resolve this problem for others:
1. Automatically checkout the master branch. It could cause a problem when developing a feature (maybe handle this with a flat)
2. Output a warning into the command line when not on the master branch

**Comment by Ruesa18** [comment]
@tuxes3 and @s4mpl3d decided that option 2 will be implemented 👍

**Comment by s4mpl3d** [comment]
resolved with #50
