### ISSUE TITLE
replace docker-sync with Mutagen

### ISSUE THREAD

**Issue by xarem** [whatwedo/dde#5]
TBD

https://mutagen.io

**Comment by lukasluecke** [comment]
https://mutagen.io/documentation/transports/docker/
https://de.slideshare.net/radekb/docker-for-mac-local-developer-environment-optimization

**Comment by lukasluecke** [comment]
With the release of [Mutagen 0.10.0](https://github.com/mutagen-io/mutagen/releases/tag/v0.10.0)  there are now extended configuration options and also orchestration support, which should make it easier to integrate into the dde process flow.

**Comment by lukasluecke** [comment]
Should work similar to the following
---
- On `dde start`
- Check if `mutagen.yml` exists in project directory
- Check if `mutagen` command / binary exists, else throw with link to install
- Run `mutagen project start` after `docker-compose up`
---
- On `dde stop`
- [...] Same check logic as above
- Run `mutagen project terminate` before ´docker-compose down`
---
Then projects can choose wether or not to use docker-sync or mutagen by using the respective config file (or even mixing them by using both).

**Comment by lukasluecke** [comment]
Also we should probably provide an example of the [mutagen.yml](https://github.com/mutagen-io/mutagen/blob/2070406df444698584dad2d1e656ae9d1aeece95/mutagen.yml) file.

**Comment by s4mpl3d** [comment]
I started the development of this feature. What i found out so far:

- we will have to use the mutagen-helper. Getting Permissions right without it is a pain (no default-owner beta in mutagen.yml)...

- Mutagen is started after the container is started, this could lead to problems in the future.

https://github.com/mutagen-io/mutagen/issues/41

**Comment by lukasluecke** [comment]
@s4mpl3d 

1. Nesting `permissions.defaultOwner` inside of `betaConfiguration` key should work (https://mutagen.io/documentation/orchestration/configuration/).
2. N/A
3. This would have to be considered and handled by the containers, but in most cases the tradeoff would be worth it for the hugely increased performance and stability - and we're not deprecating or removing docker-sync support yet, so for all others that's still an option.
