### ISSUE TITLE
Command for re-enabling ssh-key

### ISSUE THREAD

**Issue by Ruesa18** [whatwedo/dde#56]
If you use a passkey with your ssh key and you try to share this key with your dde, you have to run `dde system:update` pretty much every day because your ssh key is locked again.
Instead, it would be cool to have a command that just reactivates the ssh key and adds it to the docker containers again.
This would cut the waiting time because the containers would not have to be rebuilt (and downloaded again).

**Comment by s4mpl3d** [comment]
Closed by #61
