### ISSUE TITLE
Add Xdebug

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/dde#6]
Run in separate worker to improve performance: https://de.slideshare.net/radekb/docker-for-mac-local-developer-environment-optimization

**Comment by lukasluecke** [comment]
Might make sense to also include something like https://github.com/dbalabka/phpdebug-cli for CLI debugging (e.g. Symfony commands)

**Comment by lukasluecke** [comment]
```
 RUN apk add --no-cache php-xdebug@php
 RUN echo "xdebug.remote_enable=1" >> /etc/php$PHP_MAJOR_VERSION/conf.d/00_xdebug.ini
 RUN echo "xdebug.remote_host=docker.for.mac.localhost" >> /etc/php$PHP_MAJOR_VERSION/conf.d/00_xdebug.ini
```

in `configure-image.sh`

**Comment by s4mpl3d** [comment]
@lukasluecke Nginx config get's overridden by most applications. A fastcgi pass to different fpm-sockets would not work in that case. Maybe it would be better to do this on a per project basis. I will have a look at this tomorrow with @xarem

**Comment by s4mpl3d** [comment]
@lukasluecke i discussed this ticket with @xarem and we will roll it back.
Reason is xdebug should be installed in the base-image itself.
For that reason we could only support Alpine and debian like os's.
Also not every project used in dde will be a php project.
