### ISSUE TITLE
Add NPM registry proxy

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/dde#7]
https://verdaccio.org/docs/en/docker

To speed up installs

**Comment by lukasluecke** [comment]
First steps in `feature/npm-registry-proxy`, needs further work due to several concerns:
- Lockfile includes registry URL -> how to handle CI / different environments? Maybe just shadow the NPM registry inside the DDE network?
- What happens if Lockfile references a resolved file, but the proxy doesn't have it cached yet?

**Comment by lukasluecke** [comment]
Maybe we could also use something like https://www.npmjs.com/package/npm-proxy-cache - not exactly the same use-case but same direction

**Comment by lukasluecke** [comment]
https://github.com/yarnpkg/yarn/issues/5892

Seems like this will be included in Yarn v2 (Berry), and possibly not backported. Until then not sure how to proceed - except some hackery with string replacements, or just dynamic proxying.

**Comment by s4mpl3d** [comment]
Closing this issue as stale. If this is still a concern, please open a new issue
